format = """
[](#333333)\
$python\
$username\
[](bg:#444444 fg:#333333)\
$directory\
[](fg:#444444 bg:#4F4F4F)\
$git_branch\
$git_status\
[](fg:#4F4F4F bg:#F680B6)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#F680B6 bg:#F9C0D3)\
$docker_context\
[](fg:#F9C0D3 bg:#F06292)\
$time\
[ ](fg:#F06292)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#333333"
style_root = "bg:#333333"
format = '[   ]($style)'

[directory]
style = "bg:#444444"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#F9C0D3"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#4F4F4F"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4F4F4F"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#333333"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#F680B6"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#F06292"
format = '[ $time ]($style)'
