font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.0
hide_window_decorations yes
tab_bar_edge bottom
tab_bar_align left
tab_bar_margin_height 5.0 0.0
tab_bar_style powerline
tab_powerline_style round
background #0F0F0F
selection_background #F381A8
selection_foreground #000000

#black
color0 #000000
color8 #767676

#red
color1 #F06173
color9 #F27988

#green
color2  #91F061
color10 #A2F279

#yellow
color3  #F08761
color11 #F29979

#blue
color4  #F06191
color12 #F381A8

#magenta
color5  #F0DD61
color13 #F2E279

#cyan
color6  #61F0BF
color14 #79F2C9

#white
color7  #dddddd
color15 #ffffff